climbing <- read.csv("climbing.csv")
unique(climbing$day)
unique(climbing$biolrepeat)
unique(climbing$genomic)
unique(climbing$RU)

dev_assay <- read.csv("dev assay MR original.csv")
unique(dev_assay$Group)
unique(dev_assay$Day)
unique(dev_assay$Trail)
unique(dev_assay$Length)
unique(dev_assay$Width)
unique(dev_assay$Volume)

feeding_assay <- read.csv("feeding assay.csv")
unique(feeding_assay$Genotype)
unique(feeding_assay$Food)
unique(feeding_assay$Sumfeeding)
unique(feeding_assay$Sumnonfeeding)
unique(feeding_assay$G69)
unique(feeding_assay$foodcode)
unique(feeding_assay$feeding_percentage)

lifespan <- read.csv("lifespan.csv")
unique(lifespan$day)
unique(lifespan$event)
unique(lifespan$trail)
unique(lifespan$genotype)
unique(lifespan$RU)

QPCR <- read.csv("QPCR tango.csv")
unique(QPCR$Genotype)
unique(QPCR$RU)
unique(QPCR$Tango)

titanic <- read.csv("titanic.csv")
unique(titanic$id)
unique(titanic$pclass)
unique(titanic$survived)
unique(titanic$sex)
unique(titanic$age)
unique(titanic$sibsp)
unique(titanic$parch)
unique(titanic$ticket)
unique(titanic$fare)
unique(titanic$cabin)
unique(titanic$embarked)
unique(titanic$boat)
unique(titanic$body)
unique(titanic$home.dest)
